main:
  steps:
    - init:
        assign:
          - project_id: "profitscout-lx6bb"
          - region: "us-central1"

          - data_cruncher_name: "run-data-cruncher"
          - recommendations_generator_name: "recommendations-generator"
          - options_analyzer_name: "options-analyzer"
          - dashboard_generator_name: "run-dashboard-generator"
          - page_generator_name: "page-generator"
          - data_bundler_name: "data-bundler"
          - sync_to_firestore_name: "sync-to-firestore"
          - sync_options_to_firestore_name: "run-sync-options-to-firestore"
          - sync_calendar_to_firestore_name: "run-sync-calendar-to-firestore"

          # Shared result variables for parallel branches
          - recs_result: {}
          - options_analyzer_result: {}
          - dashboard_result: {}
          - page_result: {}
          - sync_main_result: {}
          - sync_options_result: {}
          - sync_calendar_result: {}

    - call_data_cruncher:
        call: http.post
        args:
          url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + data_cruncher_name}
          auth:
            type: OIDC
          timeout: 900
        result: data_cruncher_result

    - parallel_content_generation:
        parallel:
          shared: [recs_result, options_analyzer_result]
          branches:
            - run_recommendations:
                steps:
                  - call_recommendations_generator:
                      call: http.post
                      args:
                        url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + recommendations_generator_name}
                        auth:
                          type: OIDC
                        timeout: 900
                      result: recs_result
            - run_options_analyzer:
                steps:
                  - call_options_analyzer:
                      call: http.post
                      args:
                        url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + options_analyzer_name}
                        auth:
                          type: OIDC
                        timeout: 900
                      result: options_analyzer_result

    - parallel_json_assembly:
        parallel:
          shared: [dashboard_result, page_result]
          branches:
            - run_dashboard_generator:
                steps:
                  - call_dashboard_generator:
                      call: http.post
                      args:
                        url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + dashboard_generator_name}
                        auth:
                          type: OIDC
                        timeout: 900
                      result: dashboard_result
            - run_page_generator:
                steps:
                  - call_page_generator:
                      call: http.post
                      args:
                        url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + page_generator_name}
                        auth:
                          type: OIDC
                        timeout: 900
                      result: page_result

    - call_data_bundler:
        call: http.post
        args:
          url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + data_bundler_name}
          auth:
            type: OIDC
          timeout: 900
        result: data_bundler_result

    - final_sync:
        parallel:
          shared: [sync_main_result, sync_options_result, sync_calendar_result]
          branches:
            - run_sync_main:
                steps:
                  - call_sync_to_firestore:
                      call: http.post
                      args:
                        url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + sync_to_firestore_name}
                        auth:
                          type: OIDC
                        timeout: 900
                        body:
                          full_reset: false
                      result: sync_main_result
            - run_sync_options:
                steps:
                  - call_sync_options_to_firestore:
                      call: http.post
                      args:
                        url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + sync_options_to_firestore_name}
                        auth:
                          type: OIDC
                        timeout: 900
                        body:
                          full_reset: false
                      result: sync_options_result
            - run_sync_calendar:
                steps:
                  - call_sync_calendar_to_firestore:
                      call: http.post
                      args:
                        url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + sync_calendar_to_firestore_name}
                        auth:
                          type: OIDC
                        timeout: 900
                      result: sync_calendar_result

    - log_finish:
        call: sys.log
        args:
          text: "Serving layer workflow finished successfully."

    - done:
        return: "Workflow finished successfully." 