main:
  steps:
    - init:
        assign:
          - project_id: "profitscout-lx6bb"
          - region: "us-central1"
          - data_cruncher_name: "run-data-cruncher"
          - price_chart_generator_name: "run-price-chart-generator"
          - revenue_chart_generator_name: "run-revenue-chart-generator"
          - momentum_chart_generator_name: "run-momentum-chart-generator"
          - recommendations_generator_name: "recommendations-generator"
          - dashboard_generator_name: "run-dashboard-generator"
          - page_generator_name: "page-generator"
          - data_bundler_name: "data-bundler"
          - sync_to_firestore_name: "sync-to-firestore"
          - sync_options_to_firestore_name: "run-sync-options-to-firestore"
          - sync_calendar_to_firestore_name: "run-sync-calendar-to-firestore"

    - call_data_cruncher:
        call: http.post
        args:
          url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + data_cruncher_name}
          auth: {type: OIDC}
          timeout: 900
        result: data_cruncher_result

    - parallel_content_generation:
        parallel:
          - call_recommendations_generator:
              call: http.post
              args:
                url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + recommendations_generator_name}
                auth: {type: OIDC}
                timeout: 900
          - call_price_chart_generator:
              call: http.post
              args:
                url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + price_chart_generator_name}
                auth: {type: OIDC}
                timeout: 900
          - call_revenue_chart_generator:
              call: http.post
              args:
                url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + revenue_chart_generator_name}
                auth: {type: OIDC}
                timeout: 900
          - call_momentum_chart_generator:
              call: http.post
              args:
                url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + momentum_chart_generator_name}
                auth: {type: OIDC}
                timeout: 900
        result: parallel_content_result

    - parallel_json_assembly:
        parallel:
          - call_dashboard_generator:
              call: http.post
              args:
                url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + dashboard_generator_name}
                auth: {type: OIDC}
                timeout: 900
          - call_page_generator:
              call: http.post
              args:
                url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + page_generator_name}
                auth: {type: OIDC}
                timeout: 900
        result: parallel_assembly_result

    - call_data_bundler:
        call: http.post
        args:
          url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + data_bundler_name}
          auth: {type: OIDC}
          timeout: 900
        result: data_bundler_result

    - final_sync:
        parallel:
          - call_sync_to_firestore:
              call: http.post
              args:
                url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + sync_to_firestore_name}
                auth: {type: OIDC}
                timeout: 900
                body:
                  full_reset: false
          - call_sync_options_to_firestore:
              call: http.post
              args:
                url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + sync_options_to_firestore_name}
                auth: {type: OIDC}
                timeout: 900
                body:
                  full_reset: false
          - call_sync_calendar_to_firestore:
              call: http.post
              args:
                url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/" + sync_calendar_to_firestore_name}
                auth: {type: OIDC}
                timeout: 900
        result: final_sync_result

    - log_finish:
        call: sys.log
        args:
          text: "Serving layer workflow finished successfully."
    - done:
        return: "Workflow finished successfully."